<a href="https://colab.research.google.com/github/2303A51621/2303A51621-batch-22/blob/main/22%5C08%5C2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr1=np.array([1,2,3,4])
print("1D Array:",arr1)

1D Array: [1 2 3 4]


In [2]:
arr2=np.array([[1,2,3],[4,5,6]])
print("2D Array:\n",arr2)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [3]:
zeros_arr=np.zeros((3,3))
print("Zeros Array:\n",zeros_arr)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
ones_arr=np.ones((2,4))
print("Ones Array:\n",ones_arr)

Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
arr = np.array([[1,2,3],[4,5,6]])
print("shape:",arr.shape)
print("Dimension:",arr.ndim)
print("Data Type:",arr.dtype)
print("size:",arr.size)
print("Item Size:",arr.itemsize)

shape: (2, 3)
Dimension: 2
Data Type: int64
size: 6
Item Size: 8


Array Attributes