<a href="https://colab.research.google.com/github/2303A51621/2303A51621-batch-22/blob/main/lab02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

marks = np.array([
    [85, 78, 92],
    [58, 64, 70],
    [90, 88, 95],
    [76, 80, 85],
    [69, 72, 60]
])

print("Student Marks:\n", marks)

average_marks = np.mean(marks, axis=1)
min_marks = np.min(marks, axis=1)
max_marks = np.max(marks, axis=1)

print("\nAverage Marks per Student:", average_marks)
print("Minimum Marks per Student:", min_marks)
print("Maximum Marks per Student:", max_marks)

student_1_3_marks = marks[[0, 2]]
print("\nMarks of 1st and 3rd Students:\n", student_1_3_marks)

above_80 = np.any(marks > 80, axis=1)
students_above_80 = marks[above_80]
print("\nStudents scoring above 80 in any subject:\n", students_above_80)

subject_wise = marks.T
print("\nSubject-wise Performance (Each row = subject):\n", subject_wise)

subject_names = ['Math', 'Science', 'English']
for i, subject in enumerate(subject_names):
    print(f"\n{subject} - Avg: {np.mean(subject_wise[i]):.2f}, Min: {np.min(subject_wise[i])}, Max: {np.max(subject_wise[i])}")


Student Marks:
 [[85 78 92]
 [58 64 70]
 [90 88 95]
 [76 80 85]
 [69 72 60]]

Average Marks per Student: [85.         64.         91.         80.33333333 67.        ]
Minimum Marks per Student: [78 58 88 76 60]
Maximum Marks per Student: [92 70 95 85 72]

Marks of 1st and 3rd Students:
 [[85 78 92]
 [90 88 95]]

Students scoring above 80 in any subject:
 [[85 78 92]
 [90 88 95]
 [76 80 85]]

Subject-wise Performance (Each row = subject):
 [[85 58 90 76 69]
 [78 64 88 80 72]
 [92 70 95 85 60]]

Math - Avg: 75.60, Min: 58, Max: 90

Science - Avg: 76.40, Min: 64, Max: 88

English - Avg: 80.40, Min: 60, Max: 95
