<a href="https://colab.research.google.com/github/2303A51621/2303A51621-batch-22/blob/main/lab03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

np.random.seed(42)
scores = np.random.randint(50, 101, (4, 4))
print("Scores:\n", scores)

row_means = np.mean(scores, axis=1)
col_means = np.mean(scores, axis=0)
print("Row Means:", row_means)
print("Column Means:", col_means)

std_dev = np.std(scores)
variance = np.var(scores)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

global_min = np.min(scores)
global_max = np.max(scores)
min_index = np.unravel_index(np.argmin(scores), scores.shape)
max_index = np.unravel_index(np.argmax(scores), scores.shape)

print("Min:", global_min, "at", min_index)
print("Max:", global_max, "at", max_index)


Scores:
 [[88 78 64 92]
 [57 70 88 68]
 [72 60 60 73]
 [85 89 73 52]]
Row Means: [80.5  70.75 66.25 74.75]
Column Means: [75.5  74.25 71.25 71.25]
Standard Deviation: 12.214073593605043
Variance: 149.18359375
Min: 52 at (np.int64(3), np.int64(3))
Max: 92 at (np.int64(0), np.int64(3))


In [2]:
import numpy as np

np.random.seed(42)
image = np.random.randint(0, 256, (3, 3, 3))
print("Image:\n", image)

red = image[:, :, 0]
green = image[:, :, 1]
blue = image[:, :, 2]
print("\nRed Channel:\n", red)
print("Green Channel:\n", green)
print("Blue Channel:\n", blue)

avg_red = np.mean(red)
avg_green = np.mean(green)
avg_blue = np.mean(blue)
print("\nAverage Red:", avg_red)
print("Average Green:", avg_green)
print("Average Blue:", avg_blue)

bright_image = np.clip(image + 50, 0, 255)
print("\nBrightened Image:\n", bright_image)


Image:
 [[[102 179  92]
  [ 14 106  71]
  [188  20 102]]

 [[121 210 214]
  [ 74 202  87]
  [116  99 103]]

 [[151 130 149]
  [ 52   1  87]
  [235 157  37]]]

Red Channel:
 [[102  14 188]
 [121  74 116]
 [151  52 235]]
Green Channel:
 [[179 106  20]
 [210 202  99]
 [130   1 157]]
Blue Channel:
 [[ 92  71 102]
 [214  87 103]
 [149  87  37]]

Average Red: 117.0
Average Green: 122.66666666666667
Average Blue: 104.66666666666667

Brightened Image:
 [[[152 229 142]
  [ 64 156 121]
  [238  70 152]]

 [[171 255 255]
  [124 252 137]
  [166 149 153]]

 [[201 180 199]
  [102  51 137]
  [255 207  87]]]
